name: Deployment pipeline

on:
  push:
    branches:
      - main

env:
  SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test Server
        env:
          TEST_MONGODB_URI: mongodb://localhost:27017/test
        run: npm run test:server
      - name: Test Client
        run: npm run test:client
      - name: Test E2E
        env:
          TEST_MONGODB_URI: mongodb://localhost:27017/test
          PORT: 3003
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
